USE [Empresa_Ejemplo]
GO

/****** Object:  Table [dbo].[STA11_DEFECTO]    Script Date: 23/10/2019 20:07:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[STA11_DEFECTO](
	[ID_STA11_DEFECTO] [dbo].[D_ID] NOT NULL,
	[COD_STA11_DEFECTO] [dbo].[D_CODIGO] NOT NULL,
	[DESC_STA11_DEFECTO] [dbo].[D_DESCRIPCION] NULL,
	[FILLER] [varchar](100) NULL,
	[ALI_NO_CAT] [dbo].[ENTERO_TG] NULL,
	[CL_SIAP_CP] [varchar](3) NULL,
	[CL_SIAP_GV] [varchar](3) NULL,
	[COD_ACTIVI] [dbo].[ENTERO_TG] NULL,
	[COD_IB] [dbo].[ENTERO_TG] NULL,
	[COD_IB3] [dbo].[ENTERO_TG] NULL,
	[COD_II] [dbo].[ENTERO_TG] NULL,
	[COD_II_CO] [dbo].[ENTERO_TG] NULL,
	[COD_IVA] [dbo].[ENTERO_TG] NULL,
	[COD_IVA_CO] [dbo].[ENTERO_TG] NULL,
	[COD_S_II] [dbo].[ENTERO_TG] NULL,
	[COD_S_II_C] [dbo].[ENTERO_TG] NULL,
	[COD_S_IVA] [dbo].[ENTERO_TG] NULL,
	[COD_S_IV_C] [dbo].[ENTERO_TG] NULL,
	[COMISION_V] [dbo].[DECIMAL_TG] NULL,
	[CTA_COMPRA] [dbo].[ENTEROXL_TG] NULL,
	[CTA_VENTAS] [dbo].[ENTEROXL_TG] NULL,
	[CTO_COMPRA] [varchar](10) NULL,
	[CTO_VENTAS] [varchar](10) NULL,
	[DESCUENTO] [dbo].[DECIMAL_TG] NULL,
	[DESTI_ART] [bit] NULL,
	[EQUIVALE_V] [dbo].[DECIMAL_TG] NULL,
	[ESCALA_1] [varchar](2) NULL,
	[ESCALA_2] [varchar](2) NULL,
	[FACT_IMPOR] [bit] NULL,
	[GEN_IB] [bit] NULL,
	[GEN_IB3] [bit] NULL,
	[IMPUESTO_I] [dbo].[DECIMAL_TG] NULL,
	[IMPUEST_IC] [dbo].[DECIMAL_TG] NULL,
	[PERC_NO_CA] [bit] NULL,
	[PERFIL] [varchar](1) NULL,
	[PORC_DESVI] [dbo].[DECIMAL_TG] NULL,
	[PORC_SCRAP] [dbo].[DECIMAL_TG] NULL,
	[PORC_UTILI] [dbo].[DECIMAL_TG] NULL,
	[PROMODESDE] [datetime] NULL,
	[PROMOHASTA] [datetime] NULL,
	[PTO_PEDIDO] [dbo].[DECIMAL_TG] NULL,
	[RET_RNI] [bit] NULL,
	[RET_RNI_CO] [dbo].[ENTERO_TG] NULL,
	[STOCK] [bit] NULL,
	[STOCK_MAXI] [dbo].[DECIMAL_TG] NULL,
	[STOCK_MINI] [dbo].[DECIMAL_TG] NULL,
	[TIPO_PROMO] [varchar](1) NULL,
	[USA_ESC] [varchar](1) NULL,
	[USA_PARTID] [bit] NULL,
	[USA_SCRAP] [bit] NULL,
	[USA_SERIE] [bit] NULL,
	[RENTA_UM_S] [varchar](1) NULL,
	[RENTA_UM_V] [varchar](1) NULL,
	[RENTA_PROD] [varchar](6) NULL,
	[RENTA_EQ_S] [dbo].[DECIMAL_TG] NULL,
	[RENTA_EQ_V] [dbo].[DECIMAL_TG] NULL,
	[GENERACOT] [bit] NULL,
	[USA_CTRPRE] [bit] NULL,
	[COD_II_V_2] [dbo].[ENTERO_TG] NULL,
	[COD_SII_V2] [dbo].[ENTERO_TG] NULL,
	[IMP_II_V_2] [dbo].[DECIMAL_TG] NULL,
	[BASE] [varchar](15) NULL,
	[VALOR1] [varchar](10) NULL,
	[VALOR2] [varchar](10) NULL,
	[MET_DES_PA] [varchar](3) NULL,
	[ORD_DES_PA] [varchar](1) NULL,
	[AFIP_UM_S] [dbo].[ENTERO_TG] NULL,
	[AFIP_UM_V] [dbo].[ENTERO_TG] NULL,
	[AFIP_EQ_S] [dbo].[DECIMAL_TG] NULL,
	[AFIP_EQ_V] [dbo].[DECIMAL_TG] NULL,
	[COD_PLANTI] [varchar](10) NULL,
	[AFECTA_AF] [bit] NULL,
	[COD_TIPOB] [varchar](10) NULL,
	[REMITIBLE] [varchar](1) NULL,
	[LLEVA_DOBLE_UNIDAD_MEDIDA] [bit] NULL,
	[EQUIVALENCIA_STOCK_2] [dbo].[DECIMAL_TG] NULL,
	[ID_MEDIDA_STOCK_2] [dbo].[D_ID] NULL,
	[ID_MEDIDA_STOCK] [dbo].[D_ID] NULL,
	[ID_MEDIDA_VENTAS] [dbo].[D_ID] NULL,
	[PROMO_MENU] [varchar](1) NULL,
	[DESCARGA_NEGATIVO_STOCK] [bit] NULL,
	[DESCARGA_NEGATIVO_VENTAS] [bit] NULL,
	[ID_TYPS] [dbo].[D_ID] NULL,
	[COD_STA11] [varchar](15) NULL,
	[DESCRIPCIO] [varchar](30) NULL,
	[DESC_ADIC] [varchar](20) NULL,
	[GENERAR_CODIGO_ARTICULO] [char](1) NULL,
	[RELACION_UNIDADES_STOCK] [varchar](1) NULL,
	[DESVIO_CONTROL_UNIDADES_STOCK] [dbo].[DECIMAL_TG] NULL,
	[DESVIO_CIERRE_PEDIDOS] [dbo].[DECIMAL_TG] NULL,
	[ID_MEDIDA_CONTROL_STOCK] [dbo].[D_ID] NULL,
	[USA_CONTROL_UNIDADES_STOCK] [bit] NULL,
	[PRODUCTO_TERMINADO_COT] [varchar](1) NULL,
	[COD_NCM] [varchar](11) NULL,
	[SERIE_DESC_ADICIONAL_1] [varchar](25) NULL,
	[SERIE_DESC_ADICIONAL_2] [varchar](25) NULL,
	[EGRESO_MODIFICA_PARTIDA_PROPUESTA] [varchar](1) NULL,
	[CALCULA_CM] [bit] NULL,
	[ORIGEN_PARA_CM] [varchar](1) NULL,
	[PUBLICA_WEB_PEDIDO] [varchar](1) NULL,
	[SINCRONIZA_WEB_PEDIDO] [varchar](1) NULL,
	[ID_ACTIVIDAD_DGI] [dbo].[D_ID] NULL,
	[ID_CODIGO_ITEM_TURISMO] [dbo].[D_ID] NULL,
	[ID_TIPO_UNIDAD_TURISMO] [dbo].[D_ID] NULL,
	[ID_TIPO_ITEM_AFIP] [dbo].[D_ID] NULL,
 CONSTRAINT [PK_STA11_DEFECTO] PRIMARY KEY CLUSTERED 
(
	[ID_STA11_DEFECTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  DEFAULT (NEXT VALUE FOR [SEQUENCE_STA11_DEFECTO]) FOR [ID_STA11_DEFECTO]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__FILLE__7C48823F]  DEFAULT ('') FOR [FILLER]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__ALI_N__7D3CA678]  DEFAULT ((0)) FOR [ALI_NO_CAT]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__CL_SI__7E30CAB1]  DEFAULT ('') FOR [CL_SIAP_CP]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__CL_SI__7F24EEEA]  DEFAULT ('') FOR [CL_SIAP_GV]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_A__00191323]  DEFAULT ((0)) FOR [COD_ACTIVI]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_I__010D375C]  DEFAULT ((0)) FOR [COD_IB]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_I__02015B95]  DEFAULT ((0)) FOR [COD_IB3]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_I__02F57FCE]  DEFAULT ((0)) FOR [COD_II]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_I__03E9A407]  DEFAULT ((0)) FOR [COD_II_CO]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_I__04DDC840]  DEFAULT ((0)) FOR [COD_IVA]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_I__05D1EC79]  DEFAULT ((0)) FOR [COD_IVA_CO]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_S__06C610B2]  DEFAULT ((0)) FOR [COD_S_II]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_S__07BA34EB]  DEFAULT ((0)) FOR [COD_S_II_C]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_S__08AE5924]  DEFAULT ((0)) FOR [COD_S_IVA]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_S__09A27D5D]  DEFAULT ((0)) FOR [COD_S_IV_C]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COMIS__0A96A196]  DEFAULT ((0)) FOR [COMISION_V]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__CTA_C__0B8AC5CF]  DEFAULT ((0)) FOR [CTA_COMPRA]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__CTA_V__0C7EEA08]  DEFAULT ((0)) FOR [CTA_VENTAS]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__CTO_C__0D730E41]  DEFAULT ('') FOR [CTO_COMPRA]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__CTO_V__0E67327A]  DEFAULT ('') FOR [CTO_VENTAS]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__DESCU__0F5B56B3]  DEFAULT ((0)) FOR [DESCUENTO]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__DESTI__104F7AEC]  DEFAULT ((0)) FOR [DESTI_ART]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__EQUIV__11439F25]  DEFAULT ((0)) FOR [EQUIVALE_V]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__ESCAL__1237C35E]  DEFAULT ('') FOR [ESCALA_1]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__ESCAL__132BE797]  DEFAULT ('') FOR [ESCALA_2]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__FACT___14200BD0]  DEFAULT ((0)) FOR [FACT_IMPOR]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__GEN_I__15143009]  DEFAULT ((0)) FOR [GEN_IB]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__GEN_I__16085442]  DEFAULT ((0)) FOR [GEN_IB3]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__IMPUE__16FC787B]  DEFAULT ((0)) FOR [IMPUESTO_I]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__IMPUE__17F09CB4]  DEFAULT ((0)) FOR [IMPUEST_IC]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__PERC___18E4C0ED]  DEFAULT ((0)) FOR [PERC_NO_CA]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__PERFI__19D8E526]  DEFAULT ('') FOR [PERFIL]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__PORC___1ACD095F]  DEFAULT ((0)) FOR [PORC_DESVI]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__PORC___1BC12D98]  DEFAULT ((0)) FOR [PORC_SCRAP]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__PORC___1CB551D1]  DEFAULT ((0)) FOR [PORC_UTILI]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__PROMO__1DA9760A]  DEFAULT ('1800/01/01') FOR [PROMODESDE]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__PROMO__1E9D9A43]  DEFAULT ('1800/01/01') FOR [PROMOHASTA]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__PTO_P__1F91BE7C]  DEFAULT ((0)) FOR [PTO_PEDIDO]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__RET_R__2085E2B5]  DEFAULT ((0)) FOR [RET_RNI]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__RET_R__217A06EE]  DEFAULT ((0)) FOR [RET_RNI_CO]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__STOCK__226E2B27]  DEFAULT ((0)) FOR [STOCK]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__STOCK__23624F60]  DEFAULT ((0)) FOR [STOCK_MAXI]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__STOCK__24567399]  DEFAULT ((0)) FOR [STOCK_MINI]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__TIPO___254A97D2]  DEFAULT ('') FOR [TIPO_PROMO]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__USA_E__263EBC0B]  DEFAULT ('') FOR [USA_ESC]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__USA_P__2732E044]  DEFAULT ((0)) FOR [USA_PARTID]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__USA_S__2827047D]  DEFAULT ((0)) FOR [USA_SCRAP]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__USA_S__291B28B6]  DEFAULT ((0)) FOR [USA_SERIE]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__RENTA__2A0F4CEF]  DEFAULT ('') FOR [RENTA_UM_S]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__RENTA__2B037128]  DEFAULT ('') FOR [RENTA_UM_V]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__RENTA__2BF79561]  DEFAULT ('') FOR [RENTA_PROD]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__RENTA__2CEBB99A]  DEFAULT ((0)) FOR [RENTA_EQ_S]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__RENTA__2DDFDDD3]  DEFAULT ((0)) FOR [RENTA_EQ_V]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__GENER__2ED4020C]  DEFAULT ((0)) FOR [GENERACOT]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__USA_C__2FC82645]  DEFAULT ((0)) FOR [USA_CTRPRE]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_I__30BC4A7E]  DEFAULT ((0)) FOR [COD_II_V_2]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_S__31B06EB7]  DEFAULT ((0)) FOR [COD_SII_V2]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__IMP_I__32A492F0]  DEFAULT ((0)) FOR [IMP_II_V_2]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEFE__BASE__3398B729]  DEFAULT ('') FOR [BASE]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__VALOR__348CDB62]  DEFAULT ('') FOR [VALOR1]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__VALOR__3580FF9B]  DEFAULT ('') FOR [VALOR2]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__MET_D__367523D4]  DEFAULT ('') FOR [MET_DES_PA]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__ORD_D__3769480D]  DEFAULT ('') FOR [ORD_DES_PA]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__AFIP___385D6C46]  DEFAULT ((0)) FOR [AFIP_UM_S]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__AFIP___3951907F]  DEFAULT ((0)) FOR [AFIP_UM_V]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__AFIP___3A45B4B8]  DEFAULT ((0)) FOR [AFIP_EQ_S]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__AFIP___3B39D8F1]  DEFAULT ((0)) FOR [AFIP_EQ_V]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_P__3C2DFD2A]  DEFAULT ('') FOR [COD_PLANTI]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__AFECT__3D222163]  DEFAULT ((0)) FOR [AFECTA_AF]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_T__3E16459C]  DEFAULT ('') FOR [COD_TIPOB]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__REMIT__3F0A69D5]  DEFAULT ('') FOR [REMITIBLE]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__LLEVA__3FFE8E0E]  DEFAULT ((0)) FOR [LLEVA_DOBLE_UNIDAD_MEDIDA]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__EQUIV__40F2B247]  DEFAULT ((0)) FOR [EQUIVALENCIA_STOCK_2]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__PROMO__54F9AAF4]  DEFAULT ('') FOR [PROMO_MENU]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__DESCA__55EDCF2D]  DEFAULT ((0)) FOR [DESCARGA_NEGATIVO_STOCK]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__DESCA__56E1F366]  DEFAULT ((0)) FOR [DESCARGA_NEGATIVO_VENTAS]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_S__6900A3A1]  DEFAULT ('') FOR [COD_STA11]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__DESCR__69F4C7DA]  DEFAULT ('') FOR [DESCRIPCIO]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__DES_A__6AE8EC13]  DEFAULT ('') FOR [DESC_ADIC]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__GENER__1E6B44F6]  DEFAULT ('N') FOR [GENERAR_CODIGO_ARTICULO]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__RELAC__3FC983E4]  DEFAULT ('') FOR [RELACION_UNIDADES_STOCK]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__DESVI__40BDA81D]  DEFAULT ((0)) FOR [DESVIO_CONTROL_UNIDADES_STOCK]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__DESVI__41B1CC56]  DEFAULT ((0)) FOR [DESVIO_CIERRE_PEDIDOS]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__USA_C__42A5F08F]  DEFAULT ((0)) FOR [USA_CONTROL_UNIDADES_STOCK]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__PRODU__4952EE1E]  DEFAULT ('S') FOR [PRODUCTO_TERMINADO_COT]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__COD_N__16085442]  DEFAULT ('') FOR [COD_NCM]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__SERIE__7369237B]  DEFAULT ('') FOR [SERIE_DESC_ADICIONAL_1]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__SERIE__745D47B4]  DEFAULT ('') FOR [SERIE_DESC_ADICIONAL_2]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__EGRES__75516BED]  DEFAULT ('') FOR [EGRESO_MODIFICA_PARTIDA_PROPUESTA]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  DEFAULT ((0)) FOR [CALCULA_CM]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  DEFAULT ('') FOR [ORIGEN_PARA_CM]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__PUBLI__57ABFA6D]  DEFAULT ('N') FOR [PUBLICA_WEB_PEDIDO]
GO

ALTER TABLE [dbo].[STA11_DEFECTO] ADD  CONSTRAINT [DF__STA11_DEF__SINCR__58A01EA6]  DEFAULT ('N') FOR [SINCRONIZA_WEB_PEDIDO]
GO

ALTER TABLE [dbo].[STA11_DEFECTO]  WITH CHECK ADD  CONSTRAINT [FK_STA11_DEFECTO_ACTIVIDAD_DGI] FOREIGN KEY([ID_ACTIVIDAD_DGI])
REFERENCES [dbo].[ACTIVIDAD_DGI] ([ID_ACTIVIDAD_DGI])
GO

ALTER TABLE [dbo].[STA11_DEFECTO] CHECK CONSTRAINT [FK_STA11_DEFECTO_ACTIVIDAD_DGI]
GO

ALTER TABLE [dbo].[STA11_DEFECTO]  WITH CHECK ADD  CONSTRAINT [FK_STA11_DEFECTO_CODIGO_ITEM_TURISMO] FOREIGN KEY([ID_CODIGO_ITEM_TURISMO])
REFERENCES [dbo].[CODIGO_ITEM_TURISMO] ([ID_CODIGO_ITEM_TURISMO])
GO

ALTER TABLE [dbo].[STA11_DEFECTO] CHECK CONSTRAINT [FK_STA11_DEFECTO_CODIGO_ITEM_TURISMO]
GO

ALTER TABLE [dbo].[STA11_DEFECTO]  WITH CHECK ADD  CONSTRAINT [FK_STA11_DEFECTO_TIPO_ITEM_AFIP] FOREIGN KEY([ID_TIPO_ITEM_AFIP])
REFERENCES [dbo].[TIPO_ITEM_AFIP] ([ID_TIPO_ITEM_AFIP])
GO

ALTER TABLE [dbo].[STA11_DEFECTO] CHECK CONSTRAINT [FK_STA11_DEFECTO_TIPO_ITEM_AFIP]
GO

ALTER TABLE [dbo].[STA11_DEFECTO]  WITH CHECK ADD  CONSTRAINT [FK_STA11_DEFECTO_TIPO_UNIDAD_TURISMO] FOREIGN KEY([ID_TIPO_UNIDAD_TURISMO])
REFERENCES [dbo].[TIPO_UNIDAD_TURISMO] ([ID_TIPO_UNIDAD_TURISMO])
GO

ALTER TABLE [dbo].[STA11_DEFECTO] CHECK CONSTRAINT [FK_STA11_DEFECTO_TIPO_UNIDAD_TURISMO]
GO

