DELIMITER $$
 
DROP FUNCTION IF EXISTS `extrae_numeros` $$
CREATE FUNCTION `extrae_numeros` (VAR CHAR(100)) RETURNS CHAR(100)
DETERMINISTIC
BEGIN
  DECLARE POS INT DEFAULT 1;
  DECLARE TOTAL CHAR(100) DEFAULT '';
  DECLARE VALOR INT DEFAULT 0;
  REPEAT
    IF INSTR('0123456789', SUBSTRING(VAR, POS, 1))>0  THEN
      SET TOTAL = CONCAT(TOTAL,SUBSTRING(VAR, POS, 1));
    END IF;
    SET POS = POS + 1;
  UNTIL POS > LENGTH(VAR) END REPEAT;
  if TOTAL REGEXP '^[0-9]' then
  RETURN CAST(TOTAL AS SIGNED INTEGER);
  else
  return 0;
  end if;
END $$
 
DELIMITER ;